# Configuração de Parâmetros dos Modelos

# Configurações Gerais
general:
  random_state: 42
  test_size: 0.25
  cv_folds: 5
  n_jobs: -1

# Parâmetros SMOTE
smote:
  sampling_strategy: 'auto'
  k_neighbors: 5
  random_state: 42

# Parâmetros dos Modelos
models:
  logistic_regression:
    solver: 'liblinear'
    class_weight: 'balanced'
    max_iter: 1000
    random_state: 42
  
  random_forest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    class_weight: 'balanced'
    random_state: 42
  
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42
  
  xgboost:
    n_estimators: 200
    learning_rate: 0.05
    max_depth: 4
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
  
  svm:
    kernel: 'rbf'
    probability: true
    class_weight: 'balanced'
    random_state: 42
  
  neural_network:
    hidden_layer_sizes: [100, 50]
    activation: 'relu'
    solver: 'adam'
    max_iter: 1000
    random_state: 42
  
  knn:
    n_neighbors: 5
    weights: 'distance'

# Parâmetros para Otimização
hyperparameter_tuning:
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [3, 5, 10, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  
  xgboost:
    n_estimators: [100, 200, 300]
    learning_rate: [0.01, 0.05, 0.1]
    max_depth: [3, 4, 5, 6]
    subsample: [0.8, 0.9, 1.0]
  
  gradient_boosting:
    n_estimators: [100, 200]
    learning_rate: [0.05, 0.1, 0.2]
    max_depth: [3, 4, 5]